name: test
on: 
  push:
    branches: [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps: 
      - name: Checkout repo
        uses: action/checkout@v4
      - name: Setup Python
        uses: action/setup-python@v5
        with:
          python-version: '3.10.6'
      - name: Run Script
        run: python ./Roadmap/main.py
      - name: Comit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Update stats
          commit_user_name: Christian Santis [Automated Git Action]
          commit_user_email: c.santis91@gmail.com
          commit_author: ChSantis
          
